
[build]
  functions = "functions"
  command = "next build && next export"
  publish = "out"

[[redirects]]
  from = "/get-quote"
  to = "/comming-soon"
  status = 200


[[redirects]]
  from = "/*"
  to = "/"
  status = 200
